# Unbind the default Ctrl+b prefix
unbind C-b
# Set the new prefix to Ctrl+a
set -g prefix C-a
# Ensure Ctrl+a can be sent to other apps by pressing it twice
bind C-a send-prefix

# allow scroll wheel
set -g mouse on

# more widely available default character encoding
set -g default-terminal "screen-256color"

# vim keys (e.g. copy mode)
setw -g mode-keys vi
